### ISSUE TITLE
Question: AWS Landing Zone and Control Tower support

### ISSUE THREAD

**Issue by russomi** [walkerk1980/AWSConfigOrgsMemberAccountAggregator#1]
@walkerk1980 - 

Thanks for sharing this!  I am looking at this use case for an Add-on to the AWS Landing Zone solution and AWS Control Tower.  Has this been tested with either of those?

Thanks again for being awesome and sharing your work on GitHub!

**Comment by walkerk1980** [comment]
Sorry, no this I have not best tested this script with Control Tower.

I would recommend against using this script at this point as you should now be able to accomplish this via Delegated Administrator for Config.

https://docs.aws.amazon.com/organizations/latest/userguide/orgs_integrate_services_list.html
